'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Aggregate Key Claims blocks from Jupyter notebooks into a single markdown doc.
 *
 * Reads all numbered .ipynb files in a directory, extracts their Key Claims
 * markdown tables, and writes a unified aggregate file with one section per notebook.
 */

// Match the Key Claims block header (flexible)
const KEY_CLAIMS_PATTERNS = [
    /^##\s*Key Claims/m,
    /^##\s*Key Claims \(authoritative/m,
];

/**
 * Derive the NB label from a notebook filename.
 * "14_butterworth_cognitive_load.ipynb" → { label: "NB14", stem: "14_butterworth_cognitive_load" }
 * "11_5_chattiness_traits.ipynb" → { label: "NB11.5", stem: "11_5_chattiness_traits" }
 * "05_lhipa.ipynb" → { label: "NB05", stem: "05_lhipa" }
 */
function deriveLabel(filename) {
    const stem = filename.replace(/\.ipynb$/, '');
    // Match leading digits, optionally followed by _digits (sub-notebook)
    const m = stem.match(/^(\d+)(?:_(\d+))?/);
    if (!m) return null;

    const major = m[1];
    const minor = m[2];
    const label = minor ? `NB${major}.${minor}` : `NB${major}`;
    return { label, stem };
}

/**
 * Extract Key Claims markdown from a notebook's cells.
 * Returns the full Key Claims block as a string, or null if not found.
 */
function extractKeyClaims(notebookPath) {
    let nb;
    try {
        nb = JSON.parse(fs.readFileSync(notebookPath, 'utf-8'));
    } catch {
        return null;
    }

    const cells = nb.cells || [];
    for (const cell of cells) {
        if (cell.cell_type !== 'markdown') continue;
        const source = Array.isArray(cell.source) ? cell.source.join('') : cell.source;

        const hasKeyClaims = KEY_CLAIMS_PATTERNS.some(p => p.test(source));
        if (!hasKeyClaims) continue;

        // Extract from the Key Claims header to the end of the cell
        // (or to the next ## header within the cell)
        const lines = source.split('\n');
        let startIdx = -1;
        for (let i = 0; i < lines.length; i++) {
            if (KEY_CLAIMS_PATTERNS.some(p => p.test(lines[i]))) {
                startIdx = i;
                break;
            }
        }
        if (startIdx === -1) continue;

        // Collect lines until we hit another ## or end of cell
        const collected = [];
        for (let i = startIdx + 1; i < lines.length; i++) {
            if (/^##\s/.test(lines[i])) break;
            collected.push(lines[i]);
        }

        return collected.join('\n').trim();
    }

    return null;
}

/**
 * Count K-IDs in a Key Claims block string.
 */
function countClaims(block) {
    const matches = block.match(/\|\s*\*{0,2}K\d+\*{0,2}\s*\|/g);
    return matches ? matches.length : 0;
}

/**
 * Aggregate Key Claims from all notebooks in a directory.
 *
 * @param {string} notebookDir - Path to directory containing .ipynb files
 * @param {object} options
 * @param {string} options.output - Output file path (default: stdout)
 * @param {string} options.title - Document title
 * @returns {{ sections: Array, stats: object }}
 */
function aggregate(notebookDir, options = {}) {
    const { title = 'Notebook Key Claims' } = options;

    // Find all numbered notebooks
    const files = fs.readdirSync(notebookDir)
        .filter(f => f.endsWith('.ipynb') && /^\d+/.test(f))
        .sort((a, b) => {
            const na = parseInt(a.match(/^(\d+)/)[1]);
            const nb_num = parseInt(b.match(/^(\d+)/)[1]);
            return na - nb_num;
        });

    const sections = [];
    let totalClaims = 0;
    let notebooksWithClaims = 0;
    let notebooksWithout = 0;

    for (const file of files) {
        const info = deriveLabel(file);
        if (!info) continue;

        const fullPath = path.join(notebookDir, file);
        const block = extractKeyClaims(fullPath);

        if (block) {
            const count = countClaims(block);
            totalClaims += count;
            notebooksWithClaims++;
            sections.push({
                label: info.label,
                stem: info.stem,
                file,
                block,
                claimCount: count,
            });
        } else {
            notebooksWithout++;
        }
    }

    return {
        sections,
        stats: {
            notebooksScanned: files.length,
            notebooksWithClaims,
            notebooksWithout,
            totalClaims,
        },
    };
}

/**
 * Format the aggregate result as markdown.
 */
function formatMarkdown(result, options = {}) {
    const { title = 'Notebook Key Claims' } = options;
    const lines = [];

    lines.push(`# ${title}`);
    lines.push('');
    lines.push('> Auto-generated by `science-agent aggregate`. Do not edit manually.');
    lines.push(`> ${result.stats.notebooksWithClaims} notebooks, ${result.stats.totalClaims} claims.`);
    lines.push('');
    lines.push('**Contract:** If prose cites a value that disagrees with a row below, the prose is wrong — not the notebook.');
    lines.push('');

    // Table of contents
    lines.push('## Contents');
    lines.push('');
    for (const s of result.sections) {
        lines.push(`- [${s.label}: \`${s.stem}\`](#${s.label.toLowerCase().replace('.', '')}-${s.stem.replace(/_/g, '-')}) (${s.claimCount} claims)`);
    }
    lines.push('');

    // Sections
    for (const s of result.sections) {
        lines.push(`## ${s.label}: \`${s.stem}\``);
        lines.push('');
        lines.push(s.block);
        lines.push('');
    }

    return lines.join('\n');
}

module.exports = { aggregate, formatMarkdown, extractKeyClaims, deriveLabel };
